name: Run API Tests

on:
  push:
    branches:
      - main
      - develop

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout tests repository
        uses: actions/checkout@v4
        with:
          path: tests

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install test dependencies
        working-directory: tests
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Clone sdet project repository
        run: |
          git clone https://github.com/bondarenkokate73/simbirsoft_sdet_project.git

      - name: Build and run sdet project via Docker
        working-directory: simbirsoft_sdet_project
        run: docker-compose up -d --build

      - name: Wait for service to start
        run: |
          for i in {1..30}; do
            if curl --silent --fail http://localhost:8080/api/getAll > /dev/null; then
              echo "Service is up"
              break
            fi
            if [ $i -eq 30 ]; then
              echo "Service did not start in time" && exit 1
            fi
            echo "Waiting for service..."
            sleep 2
          done

      - name: Debug — Show test files
        run: ls -la tests

      - name: Check pytest installed
        run: which pytest

      - name: Run API Tests
        working-directory: tests
        run: pytest -n auto -v --alluredir=../allure-results

      - name: Stop Docker Containers
        if: always()
        working-directory: simbirsoft_sdet_project
        run: docker-compose down

      - name: Checkout GitHub Pages branch (for Allure history)
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Create allure-history folder if missing
        run: mkdir -p gh-pages
        if: always()

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          allure_results: allure-results
          allure_history: gh-pages
          keep_reports: 20
          clean: true

      - name: Setup Pages
        if: github.event_name != 'pull_request' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
        uses: actions/configure-pages@v4

      - name: Upload artifact
        if: github.event_name != 'pull_request' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'gh-pages'

      - name: Deploy to GitHub Pages
        id: deployment
        if: github.event_name != 'pull_request' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
        uses: actions/deploy-pages@v4
